### ISSUE TITLE
baseurl incorrect in github action

### ISSUE THREAD

**Issue by katnykiel** [imfing/hextra-starter-template#4]
I had trouble using the [Hextra github action](https://github.com/imfing/hextra-starter-template/blob/main/.github/workflows/pages.yaml) that @imfing created due to an incorrect baseURL path. 

Instead of 

`--baseURL "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"`

we need 

`--baseURL "https://${{ github.repository_owner }}.github.io/"`

to run the GitHub action. This solved the issue for me.

**Comment by imfing** [comment]
Thanks for sharing the solution. 

When your GitHub repository is named `<username>.github.io`, it's special because it gets hosted at the root domain `https://<username>.github.io/`. That's why you need to use `--baseURL "https://${{ github.repository_owner }}.github.io/"` without adding any repository name at the end.

**Comment by quai20** [comment]
> That's why you need to use `--baseURL "https://${{ github.repository_owner }}.github.io/"` without adding any repository name at the end.

Hi there, 
that's what I did but the "Home" link (top-left) still redirect to my root domain (`https://<username>.github.io/`).
Any ideas why ? 
thanks

**Comment by imfing** [comment]
@quai20 did you explicitly set the link of the logo to `/`? 
If that's the case, try comment it out.

**Comment by quai20** [comment]
Thanks that was, it. 
I thought that the "/" from the logo `link` param would direct to "baseURL".

**Comment by imfing** [comment]
@quai20 That's how your browser handles the `/` link, since it considers the `https://<username>.github.io/` as the base URL
